# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-01 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mostrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_Ingreso',
            field=models.CharField(max_length=10),
        ),
    ]
