# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-01 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mostrar', '0002_auto_20181001_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_Informacion',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
